#!/bin/bash

# Allow up to 10000 files open so analysis does not crash
ulimit -n 10000

# Determine system memory capacity
total_mem_bytes=$(sysctl -n hw.memsize) # Determine the system memory capacity
mem_75percent_gb=$((total_mem_bytes * 3 / 4 / 1024 / 1024 / 1024))

# Default value for -a flag if not provided
default_adapterSeq="CTGTCTCTTATACACATCT"
default_genomeDir=~/reference/mol/genomes/mm39/M33/PrimaryAssembly/GRCm39.primary_assembly.bowtie2
default_bowtie2indexName="GRCm39.primary_assembly.bowtie2index"
default_numCPU=$(( $(sysctl -n hw.physicalcpu_max) - 2 ))
default_mem_gb=$((mem_75percent_gb))
default_preserveTempFiles="False"
serverCredentials=""

# Function to display usage information
usage() {
    echo "This function aligns FASTQ files to a reference genome using Bowtie2. Usage: $0"
    echo "-d <dataDir>. Directory containing subdirectories with FASTQ files. REQUIRED."
    echo "-o <saveDir>. Directory to save output BAM files. REQUIRED."
    echo "-i <seqrunID>. Unique identifier for the sequencing run. REQUIRED."
    echo "-a <adapterSeq>. Adapter sequence used in the FASTQ files. Default: $default_adapterSeq"
    echo "-g <genomeDir>. Directory containing the reference genome. Default: $default_genomeDir"
    echo "-x <bowtie2indexName>. Name of the Bowtie2 index. Default: $default_bowtie2indexName"
    echo "-c <numCPU>. Number of CPUs to use for alignment. Default: $default_numCPU"
    echo "-m <mem_gb>. Max memory in GB to use. Default: $default_mem_gb"
    echo "-s <serverCredentials>. If input files are on a remote server, provide credentials as user@hostname. Default: None"
    echo "-p <preserveTempFiles>. Preserve temporary files. Default: False"
	exit 1
}

# Parse input flags
while getopts "d:o:i:a:g:x:c:m:s:p" opt; do
	case $opt in
		d) dataDir=$OPTARG ;;
		o) saveDir=$OPTARG ;;
		i) seqrunID=$OPTARG ;;
  		a) adapterSeq=$OPTARG ;;
	    g) genomeDir=$OPTARG ;;
	    x) bowtie2indexName=$OPTARG ;;
		c) numCPU=$OPTARG ;;
		m) mem_gb=$OPTARG ;;
		s) serverCredentials="$OPTARG" ;;
		p) preserveTempFiles=$OPTARG ;;
	    *) usage ;;
	esac
done

# If these variables are not set, use the default value
adapterSeq="${adapterSeq:-$default_adapterSeq}"
genomeDir="${genomeDir:-$default_genomeDir}"
bowtie2indexName="${bowtie2indexName:-$default_bowtie2indexName}"
numCPU="${numCPU:-$default_numCPU}"
mem_gb="${mem_gb:-$default_mem_gb}"
preserveTempFiles="${preserveTempFiles:-$default_preserveTempFiles}"

# Ensure all required parameters are provided
if [[ -z "$dataDir" || -z "$saveDir" || -z "$genomeDir" || -z "$adapterSeq" || -z "$bowtie2indexName" ]]; then
	usage
fi

# Debugging: Print variable values to verify they are set
printf "\033[1;34m\nParameters: $sample_name\033[0m\n" >&2
echo "dataDir: $dataDir" >&2
echo "saveDir: $saveDir" >&2
echo "adapterSeq: $adapterSeq" >&2
echo "genomeDir: $genomeDir" >&2
echo "bowtie2indexName: $bowtie2indexName" >&2
echo "numCPU: $numCPU" >&2

sudo mv /home/tibby /home/tibby.bak
sudo mkdir /home/tibby
sudo mkdir -p /media/dataA/tsmArtemis/home
sudo chown tibby:tibby /home/tibby
sudo chown tibby:tibby /media/dataA/tsmArtemis/home
sudo chmod 755 /media/dataA/tsmArtemis/home
sudo mount --bind /media/dataA/tsmArtemis/home /home/tibby
echo "/media/dataA/tsmArtemis/home /home/tibby none bind 0 0" | sudo tee -a /etc/fstab
sudo rsync -avP /home/tibby.bak/ /media/dataA/tsmArtemis/home/
sudo rm -r /home/tibby.bak
